receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  filelog:
    include: [/var/lib/docker/containers/*/*-json.log]
    poll_interval: 200ms
    start_at: beginning
    include_file_name: false
    include_file_path: false
    operators:
      - id: container-parser
        type: container
        format: docker
        add_metadata_from_filepath: false
      - id: extract_metadata_from_docker_tag
        parse_from: attributes.attrs.tag
        regex: ^(?P<name>[^\|]+)\|(?P<image_name>[^\|]+)\|(?P<id>[^$]+)$
        type: regex_parser
        if: "attributes?.attrs?.tag != nil"
      - from: attributes.name
        to: resource["docker.container.name"]
        type: move
        if: "attributes?.name != nil"
      - from: attributes.image_name
        to: resource["docker.image.name"]
        type: move
        if: "attributes?.image_name != nil"
      - from: attributes.id
        to: resource["docker.container.id"]
        type: move
        if: "attributes?.id != nil"
      - field: attributes.attrs.tag
        type: remove
        if: "attributes?.attrs?.tag != nil"
      - from: attributes.log
        to: body
        type: move

  hostmetrics:
    # Tell the scrapers to look at the mounted volume, not the container's /
    root_path: /hostfs
    scrapers:
      cpu:
      memory:
      load:
      network:
      disk:
      filesystem:

processors:
  batch:

exporters:
  otlp_http/loki:
    endpoint: loki:3100/loki/api/v1/push
    tls:
      insecure: true

  otlp_grpc/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp_http/prometheus:
    # Push metrics to Prometheus's OTLP receiver
    metrics_endpoint: prometheus:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlp_http/loki]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/tempo]

    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlp_http/prometheus]

  telemetry:
    logs:
      level: WARN
